"use client";

import { useEffect, useMemo, useState } from "react";
import { decompressDevLogs } from "@/lib/devlogs-compression";
import type { CapturedLogs } from "./DevToolsPanel";

interface SopGuideModalProps {
  isOpen: boolean;
  onClose: () => void;
  capture: {
    title: string;
    site_url?: string | null;
    created_at: string;
    dev_logs?: CapturedLogs;
  };
}

interface ParsedStep {
  index: number;
  verb: string;
  icon: string;
  detail: string;
  time: string;
  url?: string;
}

export function SopGuideModal({ isOpen, onClose, capture }: SopGuideModalProps) {
  const [copiedType, setCopiedType] = useState<"md" | "rich" | null>(null);
  const [rawLogs, setRawLogs] = useState<unknown[]>([]);

  useEffect(() => {
    let active = true;
    if (!capture.dev_logs) {
      setRawLogs([]);
      return;
    }

    Promise.resolve(decompressDevLogs(capture.dev_logs))
      .then((decompressed) => {
        if (!active) return;
        if (Array.isArray(decompressed)) {
          setRawLogs(decompressed);
        } else if (decompressed && typeof decompressed === "object" && Array.isArray((decompressed as Record<string, unknown>).steps)) {
          setRawLogs((decompressed as { steps: unknown[] }).steps);
        } else {
          setRawLogs([]);
        }
      })
      .catch(() => {
        if (active) setRawLogs([]);
      });

    return () => {
      active = false;
    };
  }, [capture.dev_logs]);

  const steps: ParsedStep[] = useMemo(() => {
    if (!Array.isArray(rawLogs) || rawLogs.length === 0) return [];

    const chronological = [...rawLogs]
      .map((item) => (item && typeof item === "object" ? (item as Record<string, unknown>) : null))
      .filter((item): item is Record<string, unknown> => item !== null)
      .sort((a, b) => Number(a.timestamp || 0) - Number(b.timestamp || 0));

    const stepLogs = chronological.filter(
      (l) => l.type === "step" || l.type === "navigation" || l.category === "action"
    );

    return stepLogs.map((log, idx) => {
      const rawMsg = typeof log.message === "string" ? log.message.trim() : "";
      const isNavigation = log.type === "navigation";
      const isClick = !isNavigation && /click/i.test(rawMsg);
      const isType = !isNavigation && /type|input/i.test(rawMsg);

      let verb = "Action";
      let icon = "👉";
      let detail = rawMsg || "User action";

      if (isNavigation) {
        verb = "Navigate";
        icon = "🌐";
        detail = typeof log.url === "string" ? `Go to ${log.url}` : rawMsg || "Navigate to page";
      } else if (isClick) {
        verb = "Click";
        icon = "👆";
        detail = rawMsg.replace(/^clicked on\s*/i, "");
      } else if (isType) {
        verb = "Type";
        icon = "⌨️";
        detail = rawMsg.replace(/^typed in\s*/i, "");
      }

      const timeStr =
        typeof log.time === "string"
          ? log.time
          : typeof log.timestamp === "number"
            ? `${Math.floor(log.timestamp / 60000).toString().padStart(2, "0")}:${Math.floor((log.timestamp % 60000) / 1000).toString().padStart(2, "0")}`
            : "00:00";

      return {
        index: idx + 1,
        verb,
        icon,
        detail,
        time: timeStr,
        url: typeof log.url === "string" ? log.url : undefined,
      };
    });
  }, [rawLogs]);

  if (!isOpen) return null;

  const markdownContent = `# ${capture.title || "Standard Operating Procedure"}\n*Generated by BugSnap SOP Builder*\n\n## Step-by-Step Instructions\n\n${steps
    .map((s) => `${s.index}. **[${s.time}]** ${s.icon} **${s.verb}**: ${s.detail}${s.url ? `\n   - *URL*: \`${s.url}\`` : ""}`)
    .join("\n")}`;

  const generateRichHtml = () => {
    let html = `<div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 650px; color: #1e293b;">`;
    html += `<h2 style="margin: 0 0 4px; color: #0f172a;">${capture.title || "Standard Operating Procedure"}</h2>`;
    html += `<p style="margin: 0 0 16px; font-size: 12px; color: #64748b;">Step-by-step workflow guide generated by BugSnap</p>`;
    html += `<ol style="padding-left: 20px; margin: 0; line-height: 1.6;">`;
    steps.forEach((s) => {
      html += `<li style="margin-bottom: 10px;">`;
      html += `<span style="display: inline-block; background: #e2e8f0; color: #475569; font-size: 11px; font-family: monospace; padding: 2px 6px; border-radius: 4px; margin-right: 6px;">${s.time}</span>`;
      html += `<strong>${s.verb}:</strong> ${s.detail}`;
      if (s.url) {
        html += `<div style="font-size: 11px; color: #64748b; font-family: monospace; margin-top: 2px;">URL: ${s.url}</div>`;
      }
      html += `</li>`;
    });
    html += `</ol></div>`;
    return html;
  };

  const handleCopyMarkdown = async () => {
    try {
      await navigator.clipboard.writeText(markdownContent);
      setCopiedType("md");
      setTimeout(() => setCopiedType(null), 2000);
    } catch (e) {
      console.error(e);
    }
  };

  const handleCopyRichText = async () => {
    try {
      const richHtml = generateRichHtml();
      const item = new ClipboardItem({
        "text/html": new Blob([richHtml], { type: "text/html" }),
        "text/plain": new Blob([markdownContent], { type: "text/plain" }),
      });
      await navigator.clipboard.write([item]);
      setCopiedType("rich");
      setTimeout(() => setCopiedType(null), 2000);
    } catch {
      await navigator.clipboard.writeText(markdownContent);
      setCopiedType("rich");
      setTimeout(() => setCopiedType(null), 2000);
    }
  };

  const handlePrintPdf = () => {
    const richHtml = generateRichHtml();
    const printWin = window.open("", "_blank", "width=850,height=700");
    if (printWin) {
      printWin.document.write(`
        <!DOCTYPE html>
        <html>
          <head>
            <title>${capture.title || "SOP Guide"}</title>
            <style>
              body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; padding: 40px; color: #0f172a; }
              h2 { margin-top: 0; color: #0f172a; border-bottom: 2px solid #e2e8f0; padding-bottom: 8px; font-size: 20px; }
              ol { padding-left: 24px; line-height: 1.8; font-size: 14px; }
              li { margin-bottom: 12px; }
              @media print { body { padding: 0; } }
            </style>
          </head>
          <body>
            ${richHtml}
            <script>
              window.onload = function() { window.print(); };
            </script>
          </body>
        </html>
      `);
      printWin.document.close();
    } else {
      window.print();
    }
  };

  return (
    <div
      className="fixed inset-0 z-[150] flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm animate-in fade-in duration-200"
      onClick={onClose}
    >
      <div
        className="relative w-full max-w-2xl bg-white dark:bg-neutral-900 border border-neutral-200 dark:border-neutral-800 rounded-2xl shadow-2xl overflow-hidden flex flex-col max-h-[85vh]"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="p-4 sm:p-5 border-b border-border bg-subtle/50 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 rounded-xl bg-emerald-500/15 text-emerald-600 dark:text-emerald-400 flex items-center justify-center shrink-0">
              <svg className="w-5 h-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
                <polyline points="14 2 14 8 20 8" />
                <line x1="16" y1="13" x2="8" y2="13" />
                <line x1="16" y1="17" x2="8" y2="17" />
              </svg>
            </div>
            <div>
              <h3 className="text-base font-bold text-foreground">Step-by-Step SOP Guide</h3>
              <p className="text-xs text-muted">Auto-compiled documentation from recording events</p>
            </div>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="p-1.5 rounded-lg text-muted hover:text-foreground hover:bg-subtle transition-colors"
            aria-label="Close"
          >
            <svg className="w-5 h-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>

        {/* Steps Content Body */}
        <div className="p-4 sm:p-6 overflow-y-auto flex-1 space-y-3">
          {steps.length === 0 ? (
            <div className="text-center py-12 px-4 text-muted space-y-2">
              <p className="text-sm font-semibold text-foreground">No user actions recorded</p>
              <p className="text-xs max-w-sm mx-auto">
                Clicks, typing, and navigations made during the capture session will be auto-formatted into documentation here.
              </p>
            </div>
          ) : (
            <div className="space-y-3">
              <div className="flex items-center justify-between pb-2 border-b border-border text-xs text-muted">
                <span className="font-semibold text-foreground">{capture.title}</span>
                <span>{steps.length} step{steps.length === 1 ? "" : "s"} documented</span>
              </div>
              {steps.map((step) => (
                <div
                  key={step.index}
                  className="flex items-start gap-3 p-3.5 rounded-xl border border-border/70 bg-white dark:bg-neutral-800/60 shadow-xs hover:border-emerald-500/40 transition-colors"
                >
                  <div className="w-6 h-6 rounded-md bg-emerald-50 dark:bg-emerald-950/60 text-emerald-600 dark:text-emerald-400 font-bold text-xs flex items-center justify-center shrink-0 mt-0.5">
                    {step.index}
                  </div>
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 mb-1 flex-wrap">
                      <span className="text-sm">{step.icon}</span>
                      <span className="text-xs font-bold uppercase tracking-wider text-foreground">
                        {step.verb}
                      </span>
                      <span className="text-[11px] font-mono px-2 py-0.5 rounded bg-subtle text-muted">
                        {step.time}
                      </span>
                    </div>
                    <p className="text-sm text-foreground/90 font-medium break-words">
                      {step.detail}
                    </p>
                    {step.url && (
                      <p className="text-[11px] text-muted font-mono truncate mt-1" title={step.url}>
                        {step.url}
                      </p>
                    )}
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>

        {/* Footer Actions */}
        <div className="p-4 border-t border-border bg-subtle/50 flex items-center justify-between gap-2 flex-wrap">
          <div className="flex items-center gap-2">
            <button
              type="button"
              onClick={handleCopyMarkdown}
              disabled={steps.length === 0}
              className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-border bg-white dark:bg-neutral-800 text-xs font-semibold text-foreground hover:bg-subtle shadow-xs transition-colors disabled:opacity-50"
            >
              <svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
                <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
              </svg>
              <span>{copiedType === "md" ? "Copied Markdown ✓" : "Copy Markdown"}</span>
            </button>
            <button
              type="button"
              onClick={handleCopyRichText}
              disabled={steps.length === 0}
              className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-border bg-white dark:bg-neutral-800 text-xs font-semibold text-foreground hover:bg-subtle shadow-xs transition-colors disabled:opacity-50"
            >
              <svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <path d="M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2" />
                <rect x="8" y="2" width="8" height="4" rx="1" ry="1" />
              </svg>
              <span>{copiedType === "rich" ? "Copied Rich Text ✓" : "Copy Rich Text"}</span>
            </button>
          </div>
          <button
            type="button"
            onClick={handlePrintPdf}
            disabled={steps.length === 0}
            className="inline-flex items-center gap-1.5 px-3.5 py-1.5 rounded-lg bg-emerald-600 hover:bg-emerald-700 text-white text-xs font-semibold shadow-xs transition-colors disabled:opacity-50"
          >
            <svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <polyline points="6 9 6 2 18 2 18 9" />
              <path d="M6 18H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2" />
              <rect x="6" y="14" width="12" height="8" />
            </svg>
            <span>Print / Save PDF</span>
          </button>
        </div>
      </div>
    </div>
  );
}
