"use client";

import { useEffect, useState } from "react";
import { useToast } from "@/components/Toast";
import { useT } from "@/components/I18nProvider";
import { getAdminHeaders } from "@/lib/admin-cache";

interface AiStats {
  totalSummaries: number;
  estimatedTokens: number;
  estimatedCostUsd: string;
  recentSummaries: Array<{
    id: string;
    title: string;
    type: string;
    created_at: string;
    creator_email: string;
  }>;
  topDrivers?: Array<{
    user_id: string;
    email: string;
    full_name: string;
    plan: string;
    effective_plan: string;
    ai_count: number;
    estimated_tokens: number;
    estimated_cost_usd: string;
    is_leech: boolean;
  }>;
}

interface ApiKeysStats {
  totalKeys: number;
  activeKeys: number;
  keysList: Array<{
    id: string;
    name: string;
    key_prefix: string;
    created_at: string;
    last_used_at: string | null;
    is_active: boolean;
    workspace_name: string;
  }>;
}

interface WebhooksStats {
  activeWebhooksCount: number;
}

export default function AdminAiAnalyticsPage() {
  const { showToast } = useToast();
  const { t } = useT();

  const [loading, setLoading] = useState(true);
  const [aiStats, setAiStats] = useState<AiStats | null>(null);
  const [apiKeysStats, setApiKeysStats] = useState<ApiKeysStats | null>(null);
  const [webhooksStats, setWebhooksStats] = useState<WebhooksStats | null>(null);

  useEffect(() => {
    loadAiAnalytics();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  async function loadAiAnalytics() {
    setLoading(true);
    try {
      const headers = await getAdminHeaders();
      const res = await fetch("/api/admin/ai-analytics", { headers });
      const json = await res.json();
      if (!res.ok) throw new Error(json.error || t("admin.loadFailed"));

      setAiStats(json.aiStats || null);
      setApiKeysStats(json.apiKeysStats || null);
      setWebhooksStats(json.webhooksStats || null);
    } catch (err: unknown) {
      showToast((err as Error)?.message || t("admin.loadFailed"), "error");
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 pb-3 border-b border-slate-200 dark:border-zinc-800">
        <div>
          <h2 className="text-base font-bold tracking-tight text-slate-900 dark:text-white flex items-center gap-2">
            <span>🤖 {t("admin.aiTitle")}</span>
          </h2>
          <p className="text-xs text-slate-500 dark:text-zinc-400 mt-0.5">
            {t("admin.aiDesc")}
          </p>
        </div>
        <button
          type="button"
          onClick={loadAiAnalytics}
          disabled={loading}
          className="self-start sm:self-auto px-3 py-1.5 rounded-lg border border-slate-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 hover:bg-slate-50 dark:hover:bg-zinc-800 text-xs font-semibold text-slate-700 dark:text-zinc-300 transition-colors shadow-xs cursor-pointer"
        >
          {loading ? t("admin.refreshing") : t("admin.refreshMetrics")}
        </button>
      </div>

      {/* 4 Overview Metrics */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        {/* Total AI Bug Summaries */}
        <div className="rounded-xl border border-slate-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 p-4 shadow-sm">
          <span className="text-[11px] font-bold uppercase tracking-wider text-slate-500 dark:text-zinc-400">
            {t("admin.totalAiCalls")}
          </span>
          <p className="text-2xl font-black text-indigo-600 dark:text-indigo-400 mt-1">
            {aiStats?.totalSummaries?.toLocaleString() || 0}
          </p>
          <span className="text-[10px] text-slate-400 mt-0.5 block">
            Generated by user captures
          </span>
        </div>

        {/* Estimated Token Consumption */}
        <div className="rounded-xl border border-slate-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 p-4 shadow-sm">
          <span className="text-[11px] font-bold uppercase tracking-wider text-slate-500 dark:text-zinc-400">
            {t("admin.aiTokensEstimated")}
          </span>
          <p className="text-2xl font-black text-slate-900 dark:text-white mt-1">
            {aiStats?.estimatedTokens?.toLocaleString() || 0}
          </p>
          <span className="text-[10px] text-slate-400 mt-0.5 block">
            ~1,200 tokens / prompt response
          </span>
        </div>

        {/* Estimated LLM API Cost */}
        <div className="rounded-xl border border-slate-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 p-4 shadow-sm">
          <span className="text-[11px] font-bold uppercase tracking-wider text-slate-500 dark:text-zinc-400">
            Estimated OpenAI Cost
          </span>
          <p className="text-2xl font-black text-emerald-600 dark:text-emerald-400 mt-1">
            {aiStats?.estimatedCostUsd || "$0.00"}
          </p>
          <span className="text-[10px] text-slate-400 mt-0.5 block">
            Based on blended GPT-4o-mini rates
          </span>
        </div>

        {/* Developer API Keys */}
        <div className="rounded-xl border border-slate-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 p-4 shadow-sm">
          <span className="text-[11px] font-bold uppercase tracking-wider text-slate-500 dark:text-zinc-400">
            {t("admin.apiKeys")}
          </span>
          <p className="text-2xl font-black text-slate-900 dark:text-white mt-1">
            {apiKeysStats?.activeKeys || 0}
            <span className="text-xs font-normal text-slate-400"> / {apiKeysStats?.totalKeys || 0} total</span>
          </p>
          <span className="text-[10px] text-slate-400 mt-0.5 block">
            {webhooksStats?.activeWebhooksCount || 0} active webhooks
          </span>
        </div>
      </div>

      {/* Top AI Cost Drivers / Leech Alert Section */}
      <div className="rounded-xl border border-slate-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 shadow-sm overflow-hidden">
        <div className="p-4 border-b border-slate-200 dark:border-zinc-800 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-2">
          <div>
            <h3 className="text-xs font-bold text-slate-900 dark:text-white uppercase tracking-wider flex items-center gap-2">
              <span>🔥 Top AI Cost Drivers (Heavy Consumers)</span>
              {(aiStats?.topDrivers || []).some((d) => d.is_leech) && (
                <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-amber-100 text-amber-800 dark:bg-amber-950/70 dark:text-amber-300 border border-amber-300 dark:border-amber-700 animate-pulse">
                  ⚠ Free Tier Leech Detected
                </span>
              )}
            </h3>
            <p className="text-[11px] text-slate-500 dark:text-zinc-400 mt-0.5">
              Pantau pengguna yang mengonsumsi kuota AI terbesar untuk mencegah tagihan OpenAI bocor dari akun gratis.
            </p>
          </div>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs">
            <thead className="border-b border-slate-200 dark:border-zinc-800 bg-slate-50 dark:bg-zinc-900 text-slate-500 dark:text-zinc-400 font-bold uppercase tracking-wider text-[10px]">
              <tr>
                <th className="py-3 px-4">User</th>
                <th className="py-3 px-4">Current Plan</th>
                <th className="py-3 px-4">AI Invocations</th>
                <th className="py-3 px-4">Est. Tokens</th>
                <th className="py-3 px-4">Est. USD Cost</th>
                <th className="py-3 px-4 text-right">Action</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100 dark:divide-zinc-800">
              {loading ? (
                <tr>
                  <td colSpan={6} className="p-8 text-center text-slate-400">
                    {t("common.loading")}
                  </td>
                </tr>
              ) : (aiStats?.topDrivers || []).length === 0 ? (
                <tr>
                  <td colSpan={6} className="p-8 text-center text-slate-400">
                    Belum ada data konsumsi AI.
                  </td>
                </tr>
              ) : (
                (aiStats?.topDrivers || []).map((driver) => (
                  <tr key={driver.user_id} className="hover:bg-slate-50 dark:hover:bg-zinc-800/50 transition-colors">
                    <td className="py-3 px-4 whitespace-nowrap">
                      <div className="font-bold text-slate-900 dark:text-white">
                        {driver.full_name || "Tanpa Nama"}
                      </div>
                      <div className="text-[11px] text-slate-500 dark:text-zinc-400 font-mono">
                        {driver.email}
                      </div>
                    </td>
                    <td className="py-3 px-4 whitespace-nowrap">
                      <div className="flex items-center gap-1.5">
                        <span className="px-2 py-0.5 rounded text-[10px] font-bold uppercase tracking-wider bg-slate-100 dark:bg-zinc-800 text-slate-700 dark:text-zinc-300">
                          {driver.effective_plan}
                        </span>
                        {driver.is_leech && (
                          <span
                            className="px-1.5 py-0.5 rounded text-[9px] font-bold uppercase bg-rose-100 text-rose-700 dark:bg-rose-950/60 dark:text-rose-400 border border-rose-200 dark:border-rose-900"
                            title="Akun gratis dengan konsumsi AI tinggi"
                          >
                            High Leech
                          </span>
                        )}
                      </div>
                    </td>
                    <td className="py-3 px-4 whitespace-nowrap font-bold text-slate-900 dark:text-white">
                      {driver.ai_count} calls
                    </td>
                    <td className="py-3 px-4 whitespace-nowrap font-mono text-slate-600 dark:text-zinc-400 text-[11px]">
                      ~{driver.estimated_tokens.toLocaleString()}
                    </td>
                    <td className="py-3 px-4 whitespace-nowrap font-bold text-emerald-600 dark:text-emerald-400 font-mono">
                      {driver.estimated_cost_usd}
                    </td>
                    <td className="py-3 px-4 text-right whitespace-nowrap">
                      <a
                        href="/admin/users"
                        className="px-2.5 py-1 rounded text-[11px] font-semibold bg-indigo-50 text-indigo-600 dark:bg-indigo-950/60 dark:text-indigo-400 hover:bg-indigo-100 transition-colors"
                      >
                        Manage User →
                      </a>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* Two Columns: Recent AI Summaries & Active API Keys */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Recent AI Summaries Table */}
        <div className="rounded-xl border border-slate-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 shadow-sm overflow-hidden flex flex-col">
          <div className="p-4 border-b border-slate-200 dark:border-zinc-800 flex items-center justify-between">
            <div>
              <h3 className="text-xs font-bold text-slate-900 dark:text-white uppercase tracking-wider">
                Recent AI Bug Reports ({aiStats?.recentSummaries?.length || 0})
              </h3>
              <p className="text-[11px] text-slate-500 dark:text-zinc-400">
                Latest captures analyzed using the AI diagnostic engine.
              </p>
            </div>
          </div>

          <div className="overflow-x-auto flex-1">
            <table className="w-full text-left text-xs">
              <thead className="border-b border-slate-200 dark:border-zinc-800 bg-slate-50 dark:bg-zinc-900 text-slate-500 dark:text-zinc-400 font-bold uppercase tracking-wider text-[10px]">
                <tr>
                  <th className="py-3 px-4">Capture</th>
                  <th className="py-3 px-4">Author</th>
                  <th className="py-3 px-4">Date</th>
                  <th className="py-3 px-4 text-right">View</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100 dark:divide-zinc-800">
                {loading ? (
                  <tr>
                    <td colSpan={4} className="p-8 text-center text-slate-400">
                      {t("common.loading")}
                    </td>
                  </tr>
                ) : (aiStats?.recentSummaries || []).length === 0 ? (
                  <tr>
                    <td colSpan={4} className="p-8 text-center text-slate-400">
                      No AI summaries generated yet.
                    </td>
                  </tr>
                ) : (
                  (aiStats?.recentSummaries || []).map((item) => (
                    <tr key={item.id} className="hover:bg-slate-50 dark:hover:bg-zinc-800/50 transition-colors">
                      <td className="py-3 px-4 whitespace-nowrap">
                        <div className="font-bold text-slate-900 dark:text-white max-w-[200px] truncate">
                          {item.title || "Untitled Capture"}
                        </div>
                        <div className="text-[10px] text-slate-400 font-mono">
                          {item.type.includes("video") ? "📹 Video" : "📸 Screenshot"} • {item.id.slice(0, 10)}…
                        </div>
                      </td>
                      <td className="py-3 px-4 whitespace-nowrap text-slate-600 dark:text-zinc-400 font-mono text-[11px]">
                        {item.creator_email}
                      </td>
                      <td className="py-3 px-4 whitespace-nowrap text-slate-500 dark:text-zinc-400 text-[11px]">
                        {new Date(item.created_at).toLocaleDateString("id-ID", {
                          day: "2-digit",
                          month: "short",
                        })}
                      </td>
                      <td className="py-3 px-4 text-right whitespace-nowrap">
                        <a
                          href={`/v/${item.id}`}
                          target="_blank"
                          rel="noreferrer"
                          className="text-indigo-600 hover:underline text-[11px] font-semibold"
                        >
                          Open ↗
                        </a>
                      </td>
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>
        </div>

        {/* API Keys Table */}
        <div className="rounded-xl border border-slate-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 shadow-sm overflow-hidden flex flex-col">
          <div className="p-4 border-b border-slate-200 dark:border-zinc-800 flex items-center justify-between">
            <div>
              <h3 className="text-xs font-bold text-slate-900 dark:text-white uppercase tracking-wider">
                Developer API Keys ({apiKeysStats?.keysList?.length || 0})
              </h3>
              <p className="text-[11px] text-slate-500 dark:text-zinc-400">
                Active workspace API keys for CI/CD and programmatic uploads.
              </p>
            </div>
          </div>

          <div className="overflow-x-auto flex-1">
            <table className="w-full text-left text-xs">
              <thead className="border-b border-slate-200 dark:border-zinc-800 bg-slate-50 dark:bg-zinc-900 text-slate-500 dark:text-zinc-400 font-bold uppercase tracking-wider text-[10px]">
                <tr>
                  <th className="py-3 px-4">Key Name</th>
                  <th className="py-3 px-4">Workspace</th>
                  <th className="py-3 px-4">Status</th>
                  <th className="py-3 px-4">Last Used</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100 dark:divide-zinc-800">
                {loading ? (
                  <tr>
                    <td colSpan={4} className="p-8 text-center text-slate-400">
                      {t("common.loading")}
                    </td>
                  </tr>
                ) : (apiKeysStats?.keysList || []).length === 0 ? (
                  <tr>
                    <td colSpan={4} className="p-8 text-center text-slate-400">
                      No developer API keys issued yet.
                    </td>
                  </tr>
                ) : (
                  (apiKeysStats?.keysList || []).map((k) => (
                    <tr key={k.id} className="hover:bg-slate-50 dark:hover:bg-zinc-800/50 transition-colors">
                      <td className="py-3 px-4 whitespace-nowrap">
                        <div className="font-bold text-slate-900 dark:text-white">
                          {k.name || "Default Key"}
                        </div>
                        <div className="text-[10px] text-slate-400 font-mono">
                          {k.key_prefix}••••••••
                        </div>
                      </td>
                      <td className="py-3 px-4 whitespace-nowrap text-slate-600 dark:text-zinc-400">
                        {k.workspace_name}
                      </td>
                      <td className="py-3 px-4 whitespace-nowrap">
                        {k.is_active ? (
                          <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-emerald-100 text-emerald-700 dark:bg-emerald-950/60 dark:text-emerald-400">
                            ACTIVE
                          </span>
                        ) : (
                          <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-slate-100 text-slate-600 dark:bg-zinc-800 dark:text-zinc-400">
                            REVOKED
                          </span>
                        )}
                      </td>
                      <td className="py-3 px-4 whitespace-nowrap text-slate-500 dark:text-zinc-400 text-[11px]">
                        {k.last_used_at
                          ? new Date(k.last_used_at).toLocaleDateString("id-ID", {
                              day: "2-digit",
                              month: "short",
                              year: "numeric",
                            })
                          : "Never"}
                      </td>
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  );
}
